# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-05 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180505_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
