# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 00:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180505_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='d2Email',
            new_name='email',
        ),
    ]
