# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-06 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180506_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='highest_game_score',
            field=models.IntegerField(default=0),
        ),
    ]
