# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_profile_highest_game_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.IntegerField(default=0)),
                ('skill_point', models.IntegerField(default=0)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=100)),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='money',
            new_name='scores',
        ),
        migrations.AddField(
            model_name='profile',
            name='_skills',
            field=models.ManyToManyField(to='main.Skill'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sessions',
            field=models.ManyToManyField(to='main.Session'),
        ),
    ]
