# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180512_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='_skills',
        ),
        migrations.AddField(
            model_name='session',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
            preserve_default=False,
        ),
    ]
