# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-12 02:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20180512_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sessions',
        ),
        migrations.AlterField(
            model_name='session',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='main.Profile'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='main.Profile'),
        ),
    ]
