# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20180515_0512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='highest_game_score',
        ),
    ]
