# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_profile_highest_game_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
