# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-15 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20180515_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('start_date', models.TimeField()),
                ('end_date', models.TimeField()),
                ('description', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
